# Generated by Django 4.2.7 on 2023-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_actor_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="app1.actor"),
        ),
    ]
