# Generated by Django 4.2.7 on 2023-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empreg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ename", models.CharField(max_length=100)),
                ("emob", models.IntegerField()),
            ],
        ),
    ]
