# Generated by Django 4.2.7 on 2023-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("empid", models.AutoField(primary_key=True, serialize=False)),
                ("empname", models.CharField(max_length=500)),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("date_last_modified", models.DateField(default=None)),
                ("img", models.ImageField(blank=True, null=True, upload_to="")),
                ("email", models.EmailField(max_length=250)),
            ],
        ),
    ]
