# Generated by Django 4.2.7 on 2023-11-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_txt",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
