# Generated by Django 4.2.7 on 2023-11-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_user2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="User1",
        ),
    ]
